language: python
dist: xenial

python:
  - 3.6
  - 3.7

script:
  - ipython --version
  - cd ml10M/
  - ipython prepare_ml10M_data.py
  - cat meta
  - cat meta_modified_all
  - cd ..
  - cd ml20M/
  - ipython prepare_ml20M_data.py
  - cat meta
  - cat meta_modified_all
  - cd ..
