language: python
dist: xenial
sudo: false

script:
  - python --version
  - python ml10M/prepare_ml10M_data.py
  - python ml20M/prepare_ml20M_data.py

matrix:
  include:
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
