language: python
dist: xenial
sudo: false

script:
  - ipython --version
  - cd ml10M/
  - ipython prepare_ml10M_data.py
  - cat meta
  - cat meta_modified_all
  - cd ..
  - cd ml20M/
  - ipython prepare_ml20M_data.py
  - cat meta
  - cat meta_modified_all
  - cd ..

matrix:
  include:
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
