language: python
dist: xenial
sudo: false

script:
  - ipython --version
  - ipython ml10M/prepare_ml10M_data.py
  - ipython ml20M/prepare_ml20M_data.py

matrix:
  include:
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
