language: python
dist: xenial

python:
  - 3.6
  - 3.7

script:
  - ipython --version
  - jupyter --version
  - cd ml10M/
  - jupyter nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute prepare_ml10M_data.ipynb
  - cat meta
  - cat meta_modified_all
  - cd ..
  - cd ml20M/
  - jupyter nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute prepare_ml20M_data.ipynb
  - cat meta
  - cat meta_modified_all
  - cd ..
