language: python
dist: xenial

python:
  - 3.6
  - 3.7

script:
  - ipython --version
  - jupyter --version
  - cd ml10M/
  - papermill prepare_ml10M_data.ipynb prepare_ml10M_data-out.ipynb
  - cat meta
  - cat meta_modified_all
  - cd ..
  - cd no_gaps_ml10/
  - papermill prepare_ml10M_data.ipynb prepare_ml10M_data-out.ipynb
  - cat meta
  - cat meta_modified_all
  - cd ..
  - cd ml20M/
  - papermill prepare_ml20M_data.ipynb prepare_ml20M_data-out.ipynb
  - cat meta
  - cat meta_modified_all
  - cd ..
  - cd no_gaps_ml20/
  - papermill prepare_ml20M_data.ipynb prepare_ml20M_data-out.ipynb
  - cat meta
  - cat meta_modified_all
  - cd ..  
  - cd jester/
  - papermill prepare_jester_data.ipynb prepare_jester_data-out.ipynb
  - cat meta
  - cat meta_modified_all
  - cd ..
